[package]
name = "bors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# CLI
clap = { version = "4.0", features = ["env", "derive"] }

# Logging
log = "0.4"
env_logger = "0.10"

# Errors
anyhow = "1.0"
thiserror = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"

# GitHub
octocrab = "0.18"

# Web
tokio = { version = "1.21", features = ["full"] }
hyper = "0.14"
axum = "0.6"
tower = { version = "0.4", features = ["limit"] }
jsonwebtoken = "8.2"
url = "2.3"
reqwest = "0.11"

# Cryptography
sha2 = "0.10"
hmac = "0.12"
hex = "0.4"
secrecy = "0.8"
base64 = "0.21"

[dev-dependencies]
insta = "1.26"
derive_builder = "0.12"
